import type { Metadata } from 'next';
import './globals.css';
import { Modal } from '@/components/modal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={''}>
        <Modal variant={'left'} children={undefined} isVisible={true} />
        {children}
      </body>
    </html>
  );
}
